-- V016: terjemahan Inggris untuk catatan Activity Log yang dibuat sebelum detail disimpan dua bahasa (V015).
-- Hanya kalimat yang cocok dengan template bawaan sistem yang diterjemahkan; sisanya tetap Indonesia.
-- Nama, judul, dan teks ketikan pengguna tidak diubah.
UPDATE audit_logs SET detail_en = regexp_replace(detail_message, '^Login berhasil$', 'Signed in')
  WHERE detail_en IS NULL AND action_type = 'AUTH_LOGIN' AND detail_message ~ '^Login berhasil$';
UPDATE audit_logs SET detail_en = regexp_replace(detail_message, '^Login gagal untuk ''(.*)''$', 'Sign-in failed for ''\1''')
  WHERE detail_en IS NULL AND action_type = 'AUTH_LOGIN_FAILED' AND detail_message ~ '^Login gagal untuk ''(.*)''$';
UPDATE audit_logs SET detail_en = regexp_replace(detail_message, '^Registrasi baru: ''(.*)'' \((.*)\)$', 'New registration: ''\1'' (\2)')
  WHERE detail_en IS NULL AND action_type = 'AUTH_REGISTER' AND detail_message ~ '^Registrasi baru: ''(.*)'' \((.*)\)$';
UPDATE audit_logs SET detail_en = regexp_replace(detail_message, '^User ''(.*)'' mengganti password \(password sementara dari admin\)$', 'User ''\1'' changed their password (temporary password from an admin)')
  WHERE detail_en IS NULL AND action_type = 'AUTH_CHANGE_PASSWORD' AND detail_message ~ '^User ''(.*)'' mengganti password \(password sementara dari admin\)$';
UPDATE audit_logs SET detail_en = regexp_replace(detail_message, '^User ''(.*)'' mengganti password$', 'User ''\1'' changed their password')
  WHERE detail_en IS NULL AND action_type = 'AUTH_CHANGE_PASSWORD' AND detail_message ~ '^User ''(.*)'' mengganti password$';
UPDATE audit_logs SET detail_en = regexp_replace(detail_message, '^Permintaan reset password untuk ''(.*)'' dari halaman login$', 'Password reset request for ''\1'' from the sign-in page')
  WHERE detail_en IS NULL AND action_type = 'AUTH_PASSWORD_HELP' AND detail_message ~ '^Permintaan reset password untuk ''(.*)'' dari halaman login$';
UPDATE audit_logs SET detail_en = regexp_replace(detail_message, '^(.*) membuka Open Web ke (.*) \(sesi (.*)\)$', '\1 opened Open Web to \2 (session \3)')
  WHERE detail_en IS NULL AND action_type = 'OPENWEB_OPEN' AND detail_message ~ '^(.*) membuka Open Web ke (.*) \(sesi (.*)\)$';
UPDATE audit_logs SET detail_en = regexp_replace(detail_message, '^(.*) mencabut sesi Open Web (.*) -> (.*) \((.*)\)$', '\1 revoked the Open Web session \2 -> \3 (\4)')
  WHERE detail_en IS NULL AND action_type = 'OPENWEB_KILL' AND detail_message ~ '^(.*) mencabut sesi Open Web (.*) -> (.*) \((.*)\)$';
UPDATE audit_logs SET detail_en = regexp_replace(detail_message, '^(.*) menjalankan aksi ''(.*)'' pada VM (.*) di (.*)$', '\1 ran the action ''\2'' on VM \3 on \4')
  WHERE detail_en IS NULL AND action_type = 'VM_ACTION' AND detail_message ~ '^(.*) menjalankan aksi ''(.*)'' pada VM (.*) di (.*)$';
UPDATE audit_logs SET detail_en = regexp_replace(detail_message, '^(.*) menghapus VM (.*) \((.*)\) di (.*)$', '\1 deleted VM \2 (\3) on \4')
  WHERE detail_en IS NULL AND action_type = 'VM_DELETE' AND detail_message ~ '^(.*) menghapus VM (.*) \((.*)\) di (.*)$';
UPDATE audit_logs SET detail_en = regexp_replace(detail_message, '^(.*) membuat VM (.*) \((.*), (.*) clone\) dari template (\S+) di (\S+), switch ''(.*)'' (\S+)$', '\1 created VM \2 (\3, \4 clone) from template \5 on \6, switch ''\7'' \8')
  WHERE detail_en IS NULL AND action_type = 'VM_CREATE' AND detail_message ~ '^(.*) membuat VM (.*) \((.*), (.*) clone\) dari template (\S+) di (\S+), switch ''(.*)'' (\S+)$';
UPDATE audit_logs SET detail_en = regexp_replace(detail_message, '^(.*) membuat VM (.*) \((.*), (.*) clone\) dari template (\S+) di (\S+)$', '\1 created VM \2 (\3, \4 clone) from template \5 on \6')
  WHERE detail_en IS NULL AND action_type = 'VM_CREATE' AND detail_message ~ '^(.*) membuat VM (.*) \((.*), (.*) clone\) dari template (\S+) di (\S+)$';
UPDATE audit_logs SET detail_en = regexp_replace(detail_message, '^(.*) mengubah resource VM (.*) di (.*): (.*)$', '\1 changed the resources of VM \2 on \3: \4')
  WHERE detail_en IS NULL AND action_type = 'VM_RESIZE' AND detail_message ~ '^(.*) mengubah resource VM (.*) di (.*): (.*)$';
UPDATE audit_logs SET detail_en = regexp_replace(detail_message, '^(.*) mengaktifkan opsi QEMU Guest Agent pada VM (.*) di (.*)$', '\1 enabled the QEMU Guest Agent option on VM \2 on \3')
  WHERE detail_en IS NULL AND action_type = 'VM_CONFIG' AND detail_message ~ '^(.*) mengaktifkan opsi QEMU Guest Agent pada VM (.*) di (.*)$';
UPDATE audit_logs SET detail_en = regexp_replace(detail_message, '^(.*) membuat snapshot ''(.*)'' pada VM (.*) di (.*)$', '\1 created the snapshot ''\2'' on VM \3 on \4')
  WHERE detail_en IS NULL AND action_type = 'VM_SNAPSHOT' AND detail_message ~ '^(.*) membuat snapshot ''(.*)'' pada VM (.*) di (.*)$';
UPDATE audit_logs SET detail_en = regexp_replace(detail_message, '^(.*) menghapus snapshot ''(.*)'' pada VM (.*) di (.*)$', '\1 deleted the snapshot ''\2'' on VM \3 on \4')
  WHERE detail_en IS NULL AND action_type = 'VM_SNAPSHOT' AND detail_message ~ '^(.*) menghapus snapshot ''(.*)'' pada VM (.*) di (.*)$';
UPDATE audit_logs SET detail_en = regexp_replace(detail_message, '^(.*) rollback ke snapshot ''(.*)'' pada VM (.*) di (.*)$', '\1 rolled back to the snapshot ''\2'' on VM \3 on \4')
  WHERE detail_en IS NULL AND action_type = 'VM_SNAPSHOT' AND detail_message ~ '^(.*) rollback ke snapshot ''(.*)'' pada VM (.*) di (.*)$';
UPDATE audit_logs SET detail_en = replace(regexp_replace(detail_message, '^(.*) mengubah masa sewa VM (.*) \((CCD-[0-9]+)\): (.*) -> (.*) UTC$', '\1 changed the lease of VM \2 (\3): \4 -> \5 UTC'), 'tanpa batas', 'no limit')
  WHERE detail_en IS NULL AND action_type = 'VM_LEASE_UPDATE' AND detail_message ~ '^(.*) mengubah masa sewa VM (.*) \((CCD-[0-9]+)\): (.*) -> (.*) UTC$';
UPDATE audit_logs SET detail_en = regexp_replace(detail_message, '^Masa sewa VM (.*) \((CCD-[0-9]+)\) habis; VM dimatikan otomatis$', 'The lease of VM \1 (\2) expired; the VM was shut down automatically')
  WHERE detail_en IS NULL AND action_type = 'VM_LEASE_EXPIRED' AND detail_message ~ '^Masa sewa VM (.*) \((CCD-[0-9]+)\) habis; VM dimatikan otomatis$';
UPDATE audit_logs SET detail_en = regexp_replace(detail_message, '^Masa sewa VM (.*) \((CCD-[0-9]+)\) habis; VM sudah dalam keadaan mati$', 'The lease of VM \1 (\2) expired; the VM was already off')
  WHERE detail_en IS NULL AND action_type = 'VM_LEASE_EXPIRED' AND detail_message ~ '^Masa sewa VM (.*) \((CCD-[0-9]+)\) habis; VM sudah dalam keadaan mati$';
UPDATE audit_logs SET detail_en = regexp_replace(detail_message, '^Masa berlaku akun (.*) habis \((.*) UTC\); login ditolak$', 'The account \1 expired (\2 UTC); sign-in refused')
  WHERE detail_en IS NULL AND action_type = 'ACCOUNT_EXPIRED' AND detail_message ~ '^Masa berlaku akun (.*) habis \((.*) UTC\); login ditolak$';
UPDATE audit_logs SET detail_en = regexp_replace(detail_message, '^(.*) memulai pembuatan (.*) VM untuk grup (.*) dari template (.*) di (.*)$', '\1 started creating \2 VMs for the group \3 from template \4 on \5')
  WHERE detail_en IS NULL AND action_type = 'VM_BATCH_CREATE' AND detail_message ~ '^(.*) memulai pembuatan (.*) VM untuk grup (.*) dari template (.*) di (.*)$';
UPDATE audit_logs SET detail_en = regexp_replace(detail_message, '^(.*) mengulang VM yang gagal di batch #(.*)$', '\1 retried the failed VMs of batch #\2')
  WHERE detail_en IS NULL AND action_type = 'VM_BATCH_RETRY' AND detail_message ~ '^(.*) mengulang VM yang gagal di batch #(.*)$';
UPDATE audit_logs SET detail_en = regexp_replace(detail_message, '^(.*) menampilkan password VM (.*) \((.*)\)$', '\1 viewed the password of VM \2 (\3)')
  WHERE detail_en IS NULL AND action_type = 'CRED_VIEW' AND detail_message ~ '^(.*) menampilkan password VM (.*) \((.*)\)$';
UPDATE audit_logs SET detail_en = regexp_replace(detail_message, '^(.*) mengunduh kredensial VM massal batch #(.*)$', '\1 downloaded the credentials of bulk VM batch #\2')
  WHERE detail_en IS NULL AND action_type = 'CRED_VIEW' AND detail_message ~ '^(.*) mengunduh kredensial VM massal batch #(.*)$';
UPDATE audit_logs SET detail_en = regexp_replace(detail_message, '^Update credentials VM (.*) \((.*)\)$', 'Updated the credentials of VM \1 (\2)')
  WHERE detail_en IS NULL AND action_type = 'CRED_UPDATE' AND detail_message ~ '^Update credentials VM (.*) \((.*)\)$';
UPDATE audit_logs SET detail_en = regexp_replace(detail_message, '^(.*) mereset password user ''(.*)'' di dalam VM (.*) \((.*)\)$', '\1 reset the password of user ''\2'' inside VM \3 (\4)')
  WHERE detail_en IS NULL AND action_type = 'VM_PASSWORD_RESET' AND detail_message ~ '^(.*) mereset password user ''(.*)'' di dalam VM (.*) \((.*)\)$';
UPDATE audit_logs SET detail_en = regexp_replace(detail_message, '^User ''(.*)'' diganti password-nya di dalam VM (.*) untuk kredensial grup (.*)$', 'User ''\1'' had its password changed inside VM \2 for the credentials of group \3')
  WHERE detail_en IS NULL AND action_type = 'VM_PASSWORD_RESET' AND detail_message ~ '^User ''(.*)'' diganti password-nya di dalam VM (.*) untuk kredensial grup (.*)$';
UPDATE audit_logs SET detail_en = regexp_replace(detail_message, '^User ''(.*)'' dibuat di dalam VM (.*) untuk kredensial grup (.*)$', 'User ''\1'' created inside VM \2 for the credentials of group \3')
  WHERE detail_en IS NULL AND action_type = 'OS_ACCOUNT_CREATE' AND detail_message ~ '^User ''(.*)'' dibuat di dalam VM (.*) untuk kredensial grup (.*)$';
UPDATE audit_logs SET detail_en = regexp_replace(detail_message, '^Tambah OS account ''(.*)'' untuk VM (.*) \(user dibuat di dalam VM\)$', 'Added the OS account ''\1'' for VM \2 (user created inside the VM)')
  WHERE detail_en IS NULL AND action_type = 'OS_ACCOUNT_CREATE' AND detail_message ~ '^Tambah OS account ''(.*)'' untuk VM (.*) \(user dibuat di dalam VM\)$';
UPDATE audit_logs SET detail_en = regexp_replace(detail_message, '^Tambah OS account ''(.*)'' untuk VM (.*)$', 'Added the OS account ''\1'' for VM \2')
  WHERE detail_en IS NULL AND action_type = 'OS_ACCOUNT_CREATE' AND detail_message ~ '^Tambah OS account ''(.*)'' untuk VM (.*)$';
UPDATE audit_logs SET detail_en = regexp_replace(detail_message, '^Update OS account ''(.*)'' VM (.*)$', 'Updated the OS account ''\1'' of VM \2')
  WHERE detail_en IS NULL AND action_type = 'OS_ACCOUNT_UPDATE' AND detail_message ~ '^Update OS account ''(.*)'' VM (.*)$';
UPDATE audit_logs SET detail_en = regexp_replace(detail_message, '^Hapus OS account ''(.*)'' VM (.*) \(user dan folder home-nya dihapus dari dalam VM\)$', 'Deleted the OS account ''\1'' of VM \2 (the user and its home folder were deleted inside the VM)')
  WHERE detail_en IS NULL AND action_type = 'OS_ACCOUNT_DELETE' AND detail_message ~ '^Hapus OS account ''(.*)'' VM (.*) \(user dan folder home-nya dihapus dari dalam VM\)$';
UPDATE audit_logs SET detail_en = regexp_replace(detail_message, '^Hapus OS account ''(.*)'' VM (.*)$', 'Deleted the OS account ''\1'' of VM \2')
  WHERE detail_en IS NULL AND action_type = 'OS_ACCOUNT_DELETE' AND detail_message ~ '^Hapus OS account ''(.*)'' VM (.*)$';
UPDATE audit_logs SET detail_en = regexp_replace(detail_message, '^Assign VM (.*) ke user #(.*) \(otomatis dari request VPS (.*)\)$', 'Assigned VM \1 to user #\2 (automatically from VPS request \3)')
  WHERE detail_en IS NULL AND action_type = 'RBAC_ASSIGN_VM' AND detail_message ~ '^Assign VM (.*) ke user #(.*) \(otomatis dari request VPS (.*)\)$';
UPDATE audit_logs SET detail_en = regexp_replace(detail_message, '^Assign VM (.*) ke user #(.*) \(OS account #(.*)\)$', 'Assigned VM \1 to user #\2 (OS account #\3)')
  WHERE detail_en IS NULL AND action_type = 'RBAC_ASSIGN_VM' AND detail_message ~ '^Assign VM (.*) ke user #(.*) \(OS account #(.*)\)$';
UPDATE audit_logs SET detail_en = regexp_replace(detail_message, '^Assign VM (.*) ke user #(.*)$', 'Assigned VM \1 to user #\2')
  WHERE detail_en IS NULL AND action_type = 'RBAC_ASSIGN_VM' AND detail_message ~ '^Assign VM (.*) ke user #(.*)$';
UPDATE audit_logs SET detail_en = regexp_replace(detail_message, '^Unassign VM (.*) dari user #(.*)$', 'Unassigned VM \1 from user #\2')
  WHERE detail_en IS NULL AND action_type = 'RBAC_UNASSIGN_VM' AND detail_message ~ '^Unassign VM (.*) dari user #(.*)$';
UPDATE audit_logs SET detail_en = regexp_replace(detail_message, '^(.*) membuat akun ''(.*)'' dengan peran (.*)$', '\1 created the account ''\2'' with the role \3')
  WHERE detail_en IS NULL AND action_type = 'USER_CREATE' AND detail_message ~ '^(.*) membuat akun ''(.*)'' dengan peran (.*)$';
UPDATE audit_logs SET detail_en = regexp_replace(detail_message, '^(.*) menghapus akun ''(.*)''$', '\1 deleted the account ''\2''')
  WHERE detail_en IS NULL AND action_type = 'USER_DELETE' AND detail_message ~ '^(.*) menghapus akun ''(.*)''$';
UPDATE audit_logs SET detail_en = replace(replace(replace(replace(replace(replace(replace(replace(regexp_replace(detail_message, '^(.*) mengubah akun ''(.*)'': (.*)$', '\1 changed the account ''\2'': \3'), 'verifikasi dicabut', 'verification revoked'), 'diverifikasi', 'verified'), 'dinonaktifkan', 'deactivated'), 'diaktifkan', 'activated'), 'masa berlaku ', 'expiry '), 'tanpa batas', 'no limit'), 'nama ''', 'name '''), 'peran ', 'role ')
  WHERE detail_en IS NULL AND action_type = 'USER_UPDATE' AND detail_message ~ '^(.*) mengubah akun ''(.*)'': (.*)$';
UPDATE audit_logs SET detail_en = regexp_replace(detail_message, '^(.*) mereset password akun ''(.*)'' \(permintaan Lupa password\)$', '\1 reset the password of the account ''\2'' (Forgot password request)')
  WHERE detail_en IS NULL AND action_type = 'USER_PASSWORD_RESET' AND detail_message ~ '^(.*) mereset password akun ''(.*)'' \(permintaan Lupa password\)$';
UPDATE audit_logs SET detail_en = regexp_replace(detail_message, '^(.*) mereset password akun ''(.*)''$', '\1 reset the password of the account ''\2''')
  WHERE detail_en IS NULL AND action_type = 'USER_PASSWORD_RESET' AND detail_message ~ '^(.*) mereset password akun ''(.*)''$';
UPDATE audit_logs SET detail_en = regexp_replace(detail_message, '^(.*) mengganti password akun ''(.*)'' lewat Edit$', '\1 changed the password of the account ''\2'' through Edit')
  WHERE detail_en IS NULL AND action_type = 'USER_PASSWORD_RESET' AND detail_message ~ '^(.*) mengganti password akun ''(.*)'' lewat Edit$';
UPDATE audit_logs SET detail_en = regexp_replace(detail_message, '^(.*) mengabaikan permintaan reset password ''(.*)''$', '\1 dismissed the password reset request of ''\2''')
  WHERE detail_en IS NULL AND action_type = 'USER_PASSWORD_HELP_DISMISS' AND detail_message ~ '^(.*) mengabaikan permintaan reset password ''(.*)''$';
UPDATE audit_logs SET detail_en = regexp_replace(detail_message, '^(.*) mengaktifkan (.*) akun$', '\1 activated \2 accounts')
  WHERE detail_en IS NULL AND action_type = 'USER_BULK_UPDATE' AND detail_message ~ '^(.*) mengaktifkan (.*) akun$';
UPDATE audit_logs SET detail_en = regexp_replace(detail_message, '^(.*) menonaktifkan (.*) akun$', '\1 deactivated \2 accounts')
  WHERE detail_en IS NULL AND action_type = 'USER_BULK_UPDATE' AND detail_message ~ '^(.*) menonaktifkan (.*) akun$';
UPDATE audit_logs SET detail_en = regexp_replace(detail_message, '^(.*) menghapus masa berlaku (.*) akun$', '\1 removed the expiry of \2 accounts')
  WHERE detail_en IS NULL AND action_type = 'USER_BULK_UPDATE' AND detail_message ~ '^(.*) menghapus masa berlaku (.*) akun$';
UPDATE audit_logs SET detail_en = regexp_replace(detail_message, '^(.*) mengatur masa berlaku sampai (.*) (.*) akun$', '\1 set the expiry to \2 for \3 accounts')
  WHERE detail_en IS NULL AND action_type = 'USER_BULK_UPDATE' AND detail_message ~ '^(.*) mengatur masa berlaku sampai (.*) (.*) akun$';
UPDATE audit_logs SET detail_en = regexp_replace(detail_message, '^(.*) mengimpor (.*) akun ke grup (.*)$', '\1 imported \2 accounts into the group \3')
  WHERE detail_en IS NULL AND action_type = 'USER_IMPORT' AND detail_message ~ '^(.*) mengimpor (.*) akun ke grup (.*)$';
UPDATE audit_logs SET detail_en = regexp_replace(detail_message, '^(.*) mengimpor (.*) akun$', '\1 imported \2 accounts')
  WHERE detail_en IS NULL AND action_type = 'USER_IMPORT' AND detail_message ~ '^(.*) mengimpor (.*) akun$';
UPDATE audit_logs SET detail_en = replace(replace(replace(replace(regexp_replace(detail_message, '^(.*) menonaktifkan akun ''(.*)'' dan memutus semua sesinya \((.*)\): (.*)$', '\1 deactivated the account ''\2'' and disconnected all of its sessions (\3): \4'), 'dari sesi Remote ke', 'from the Remote session to'), 'dari link Open Web ke', 'from the Open Web link to'), 'dari sesi SSH di bastion', 'from the SSH session at the bastion'), ' di ', ' on ')
  WHERE detail_en IS NULL AND action_type = 'USER_LOCKOUT' AND detail_message ~ '^(.*) menonaktifkan akun ''(.*)'' dan memutus semua sesinya \((.*)\): (.*)$';
UPDATE audit_logs SET detail_en = regexp_replace(detail_message, '^(.*) membuat grup ''(.*)''$', '\1 created the group ''\2''')
  WHERE detail_en IS NULL AND action_type = 'GROUP_CREATE' AND detail_message ~ '^(.*) membuat grup ''(.*)''$';
UPDATE audit_logs SET detail_en = regexp_replace(detail_message, '^(.*) menghapus grup ''(.*)'' \((.*) anggota, (.*) VM\)$', '\1 deleted the group ''\2'' (\3 members, \4 VMs)')
  WHERE detail_en IS NULL AND action_type = 'GROUP_DELETE' AND detail_message ~ '^(.*) menghapus grup ''(.*)'' \((.*) anggota, (.*) VM\)$';
UPDATE audit_logs SET detail_en = replace(replace(regexp_replace(detail_message, '^(.*) mengubah grup ''(.*)'': (.*)$', '\1 changed the group ''\2'': \3'), 'nama ''', 'name '''), 'deskripsi diubah', 'description changed')
  WHERE detail_en IS NULL AND action_type = 'GROUP_UPDATE' AND detail_message ~ '^(.*) mengubah grup ''(.*)'': (.*)$';
UPDATE audit_logs SET detail_en = regexp_replace(detail_message, '^(.*) menambahkan ''(.*)'' ke grup ''(.*)''$', '\1 added ''\2'' to the group ''\3''')
  WHERE detail_en IS NULL AND action_type = 'GROUP_MEMBER_ADD' AND detail_message ~ '^(.*) menambahkan ''(.*)'' ke grup ''(.*)''$';
UPDATE audit_logs SET detail_en = regexp_replace(detail_message, '^(.*) mengeluarkan ''(.*)'' dari grup ''(.*)''$', '\1 removed ''\2'' from the group ''\3''')
  WHERE detail_en IS NULL AND action_type = 'GROUP_MEMBER_REMOVE' AND detail_message ~ '^(.*) mengeluarkan ''(.*)'' dari grup ''(.*)''$';
UPDATE audit_logs SET detail_en = replace(replace(regexp_replace(detail_message, '^(.*) memberi grup ''(.*)'' akses ke VM (.*) di (.*) \((.*)\)$', '\1 gave the group ''\2'' access to VM \3 on \4 (\5)'), 'kredensial bersama, akun OS', 'shared credentials, OS account'), 'akun mandiri', 'own account')
  WHERE detail_en IS NULL AND action_type = 'GROUP_VM_ADD' AND detail_message ~ '^(.*) memberi grup ''(.*)'' akses ke VM (.*) di (.*) \((.*)\)$';
UPDATE audit_logs SET detail_en = replace(replace(replace(regexp_replace(detail_message, '^(.*) mengubah akses grup ''(.*)'' ke VM (.*) di (.*) \((.*)\)$', '\1 changed the access of the group ''\2'' to VM \3 on \4 (\5)'), 'kredensial bersama, akun OS', 'shared credentials, OS account'), 'akun mandiri', 'own account'), 'password diganti', 'password changed')
  WHERE detail_en IS NULL AND action_type = 'GROUP_VM_UPDATE' AND detail_message ~ '^(.*) mengubah akses grup ''(.*)'' ke VM (.*) di (.*) \((.*)\)$';
UPDATE audit_logs SET detail_en = regexp_replace(detail_message, '^(.*) mencabut akses grup ''(.*)'' ke VM (.*) di (.*)$', '\1 revoked the access of the group ''\2'' to VM \3 on \4')
  WHERE detail_en IS NULL AND action_type = 'GROUP_VM_REMOVE' AND detail_message ~ '^(.*) mencabut akses grup ''(.*)'' ke VM (.*) di (.*)$';
UPDATE audit_logs SET detail_en = replace(replace(regexp_replace(detail_message, '^(.*) membuat switch ''(.*)'' (.*) di (.*) \(VNet (.*), internet (.*)\)$', '\1 created the switch ''\2'' \3 on \4 (VNet \5, internet \6)'), 'internet mati', 'internet off'), 'blok alamat baru', 'new address block')
  WHERE detail_en IS NULL AND action_type = 'NETWORK_CREATE' AND detail_message ~ '^(.*) membuat switch ''(.*)'' (.*) di (.*) \(VNet (.*), internet (.*)\)$';
UPDATE audit_logs SET detail_en = regexp_replace(detail_message, '^(.*) menghapus switch ''(.*)'' (.*) di (.*)$', '\1 deleted the switch ''\2'' \3 on \4')
  WHERE detail_en IS NULL AND action_type = 'NETWORK_DELETE' AND detail_message ~ '^(.*) menghapus switch ''(.*)'' (.*) di (.*)$';
UPDATE audit_logs SET detail_en = replace(replace(regexp_replace(detail_message, '^(.*) mengubah switch (.*) di (.*): (.*)$', '\1 changed the switch \2 on \3: \4'), 'nama ''', 'name '''), 'internet mati', 'internet off')
  WHERE detail_en IS NULL AND action_type = 'NETWORK_UPDATE' AND detail_message ~ '^(.*) mengubah switch (.*) di (.*): (.*)$';
UPDATE audit_logs SET detail_en = replace(regexp_replace(detail_message, '^(.*) menambah blok alamat switch (.*) di Proxmox (.*)$', '\1 added the switch address block \2 on Proxmox \3'), '(menggantikan ', '(replacing ')
  WHERE detail_en IS NULL AND action_type = 'NETWORK_POOL_ADD' AND detail_message ~ '^(.*) menambah blok alamat switch (.*) di Proxmox (.*)$';
UPDATE audit_logs SET detail_en = regexp_replace(detail_message, '^(.*) menghapus blok alamat switch (.*) dari Proxmox (.*)$', '\1 removed the switch address block \2 from Proxmox \3')
  WHERE detail_en IS NULL AND action_type = 'NETWORK_POOL_REMOVE' AND detail_message ~ '^(.*) menghapus blok alamat switch (.*) dari Proxmox (.*)$';
UPDATE audit_logs SET detail_en = regexp_replace(detail_message, '^(.*) mengubah blok alamat switch Proxmox (.*): (.*)$', '\1 changed the switch address block of Proxmox \2: \3')
  WHERE detail_en IS NULL AND action_type = 'NETWORK_POOL_UPDATE' AND detail_message ~ '^(.*) mengubah blok alamat switch Proxmox (.*): (.*)$';
UPDATE audit_logs SET detail_en = replace(replace(regexp_replace(detail_message, '^(.*) menambahkan instance Proxmox ''(.*)'' \((.*)\)$', '\1 added the Proxmox instance ''\2'' (\3)'), 'verifikasi SSL aktif', 'SSL verification on'), 'verifikasi SSL mati', 'SSL verification off')
  WHERE detail_en IS NULL AND action_type = 'PVE_INSTANCE_ADD' AND detail_message ~ '^(.*) menambahkan instance Proxmox ''(.*)'' \((.*)\)$';
UPDATE audit_logs SET detail_en = replace(replace(replace(replace(regexp_replace(detail_message, '^(.*) mengubah instance Proxmox ''(.*)'': (.*)$', '\1 changed the Proxmox instance ''\2'': \3'), 'alamat ', 'address '), 'secret token diganti', 'token secret changed'), 'verifikasi SSL aktif', 'SSL verification on'), 'verifikasi SSL mati', 'SSL verification off')
  WHERE detail_en IS NULL AND action_type = 'PVE_INSTANCE_UPDATE' AND detail_message ~ '^(.*) mengubah instance Proxmox ''(.*)'': (.*)$';
UPDATE audit_logs SET detail_en = regexp_replace(detail_message, '^(.*) menghapus instance Proxmox ''(.*)'' \((.*)\)$', '\1 deleted the Proxmox instance ''\2'' (\3)')
  WHERE detail_en IS NULL AND action_type = 'PVE_INSTANCE_DELETE' AND detail_message ~ '^(.*) menghapus instance Proxmox ''(.*)'' \((.*)\)$';
UPDATE audit_logs SET detail_en = replace(regexp_replace(detail_message, '^(.*) login ke bastion SSH dengan key (.*)$', '\1 signed in to the SSH bastion with the key \2'), '(key tidak terdaftar)', '(unregistered key)')
  WHERE detail_en IS NULL AND action_type = 'SSH_LOGIN' AND detail_message ~ '^(.*) login ke bastion SSH dengan key (.*)$';
UPDATE audit_logs SET detail_en = replace(replace(replace(replace(replace(replace(regexp_replace(detail_message, '^(.*) keluar dari bastion SSH setelah (.*), tujuan (.*)$', '\1 left the SSH bastion after \2, destination \3'), ' jam ', ' h '), ' menit', ' min'), ' detik', ' s'), 'klien tidak merespons', 'the client stopped responding'), 'koneksi terputus', 'the connection dropped'), '(key tidak terdaftar)', '(unregistered key)')
  WHERE detail_en IS NULL AND action_type = 'SSH_LOGOUT' AND detail_message ~ '^(.*) keluar dari bastion SSH setelah (.*), tujuan (.*)$';
UPDATE audit_logs SET detail_en = replace(replace(replace(replace(replace(replace(regexp_replace(detail_message, '^(.*) keluar dari bastion SSH setelah (.*), tanpa membuka VM$', '\1 left the SSH bastion after \2, without opening a VM'), ' jam ', ' h '), ' menit', ' min'), ' detik', ' s'), 'klien tidak merespons', 'the client stopped responding'), 'koneksi terputus', 'the connection dropped'), '(key tidak terdaftar)', '(unregistered key)')
  WHERE detail_en IS NULL AND action_type = 'SSH_LOGOUT' AND detail_message ~ '^(.*) keluar dari bastion SSH setelah (.*), tanpa membuka VM$';
UPDATE audit_logs SET detail_en = replace(replace(replace(replace(regexp_replace(detail_message, '^Key SSH (.*) milik (.*) ditolak bastion: (.*)$', 'SSH key \1 of \2 was rejected by the bastion: \3'), 'akun nonaktif', 'account is inactive'), 'masa berlaku akun habis', 'the account has expired'), 'akun belum diverifikasi', 'the account is not verified'), 'tidak ada VM yang bisa diakses lewat SSH', 'no VM can be reached through SSH')
  WHERE detail_en IS NULL AND action_type = 'SSH_DENIED' AND detail_message ~ '^Key SSH (.*) milik (.*) ditolak bastion: (.*)$';
UPDATE audit_logs SET detail_en = regexp_replace(detail_message, '^(.*) mencoba membuka (.*) lewat bastion SSH, ditolak karena bukan VM yang boleh diaksesnya$', '\1 tried to open \2 through the SSH bastion, refused because it is not a VM they may access')
  WHERE detail_en IS NULL AND action_type = 'SSH_DENIED' AND detail_message ~ '^(.*) mencoba membuka (.*) lewat bastion SSH, ditolak karena bukan VM yang boleh diaksesnya$';
UPDATE audit_logs SET detail_en = regexp_replace(detail_message, '^(.*) menambahkan SSH key (.*) \((.*)\)$', '\1 added the SSH key \2 (\3)')
  WHERE detail_en IS NULL AND action_type = 'SSH_KEY_ADD' AND detail_message ~ '^(.*) menambahkan SSH key (.*) \((.*)\)$';
UPDATE audit_logs SET detail_en = regexp_replace(detail_message, '^(.*) menghapus SSH key (.*) \((.*)\)$', '\1 deleted the SSH key \2 (\3)')
  WHERE detail_en IS NULL AND action_type = 'SSH_KEY_DELETE' AND detail_message ~ '^(.*) menghapus SSH key (.*) \((.*)\)$';
UPDATE audit_logs SET detail_en = regexp_replace(detail_message, '^(.*) memutus sesi SSH ''(.*)'' dari (.*) di bastion$', '\1 disconnected the SSH session of ''\2'' from \3 at the bastion')
  WHERE detail_en IS NULL AND action_type = 'SSH_KILL' AND detail_message ~ '^(.*) memutus sesi SSH ''(.*)'' dari (.*) di bastion$';
UPDATE audit_logs SET detail_en = regexp_replace(detail_message, '^Force-terminate sesi Guacamole (.*)$', 'Forcibly terminated the Guacamole session \1')
  WHERE detail_en IS NULL AND action_type = 'REMOTE_KILL' AND detail_message ~ '^Force-terminate sesi Guacamole (.*)$';
UPDATE audit_logs SET detail_en = replace(replace(replace(regexp_replace(detail_message, '^(.*) memutus sesi Remote ''(.*)'' ke (.*)$', '\1 disconnected the Remote session of ''\2'' to \3'), ' dan mencabut penugasan VM tersebut', ' and revoked that VM assignment'), '(akun OS ', '(OS account '), ' di ', ' on ')
  WHERE detail_en IS NULL AND action_type = 'REMOTE_KILL' AND detail_message ~ '^(.*) memutus sesi Remote ''(.*)'' ke (.*)$';
UPDATE audit_logs SET detail_en = regexp_replace(detail_message, '^(.*) memberi akses semua koneksi Guacamole ke (.*) akun admin$', '\1 granted access to every Guacamole connection to \2 admin accounts')
  WHERE detail_en IS NULL AND action_type = 'GUAC_GRANT_ADMINS' AND detail_message ~ '^(.*) memberi akses semua koneksi Guacamole ke (.*) akun admin$';
UPDATE audit_logs SET detail_en = regexp_replace(detail_message, '^(.*) mengekspor (.*) baris Activity Log ke CSV$', '\1 exported \2 activity log rows to CSV')
  WHERE detail_en IS NULL AND action_type = 'AUDIT_EXPORT' AND detail_message ~ '^(.*) mengekspor (.*) baris Activity Log ke CSV$';
UPDATE audit_logs SET detail_en = regexp_replace(detail_message, '^(.*) mengekspor (.*) baris riwayat (.*) ke CSV$', '\1 exported \2 \3 history rows to CSV')
  WHERE detail_en IS NULL AND action_type = 'AUDIT_EXPORT' AND detail_message ~ '^(.*) mengekspor (.*) baris riwayat (.*) ke CSV$';
UPDATE audit_logs SET detail_en = regexp_replace(detail_message, '^(.*) mengubah pengaturan sistem: (.*)$', '\1 changed the system settings: \2')
  WHERE detail_en IS NULL AND action_type = 'SYSTEM_SETTINGS_UPDATE' AND detail_message ~ '^(.*) mengubah pengaturan sistem: (.*)$';
UPDATE audit_logs SET detail_en = regexp_replace(detail_message, '^(.*) mengganti logo sistem \((.*)\)$', '\1 changed the system logo (\2)')
  WHERE detail_en IS NULL AND action_type = 'SYSTEM_LOGO_UPDATE' AND detail_message ~ '^(.*) mengganti logo sistem \((.*)\)$';
UPDATE audit_logs SET detail_en = regexp_replace(detail_message, '^(.*) menghapus logo sistem$', '\1 removed the system logo')
  WHERE detail_en IS NULL AND action_type = 'SYSTEM_LOGO_UPDATE' AND detail_message ~ '^(.*) menghapus logo sistem$';
UPDATE audit_logs SET detail_en = regexp_replace(detail_message, '^(.*) mengganti logo OS (.*) \((.*)\)$', '\1 changed the logo of OS \2 (\3)')
  WHERE detail_en IS NULL AND action_type = 'OS_LOGO_UPDATE' AND detail_message ~ '^(.*) mengganti logo OS (.*) \((.*)\)$';
UPDATE audit_logs SET detail_en = regexp_replace(detail_message, '^(.*) menghapus logo OS (.*)$', '\1 removed the logo of OS \2')
  WHERE detail_en IS NULL AND action_type = 'OS_LOGO_UPDATE' AND detail_message ~ '^(.*) menghapus logo OS (.*)$';
UPDATE audit_logs SET detail_en = regexp_replace(detail_message, '^(.*) mengubah pilihan OS Infra Request: (.*)$', '\1 changed the infrastructure request OS choices: \2')
  WHERE detail_en IS NULL AND action_type = 'OS_OPTIONS_UPDATE' AND detail_message ~ '^(.*) mengubah pilihan OS Infra Request: (.*)$';
UPDATE audit_logs SET detail_en = regexp_replace(detail_message, '^(.*) mengubah kategori helpdesk: (.*)$', '\1 changed the helpdesk categories: \2')
  WHERE detail_en IS NULL AND action_type = 'TICKET_CATEGORIES_UPDATE' AND detail_message ~ '^(.*) mengubah kategori helpdesk: (.*)$';
UPDATE audit_logs SET detail_en = regexp_replace(detail_message, '^Tiket (.*) dibuat: (.*)$', 'Ticket \1 created: \2')
  WHERE detail_en IS NULL AND action_type = 'TICKET_CREATE' AND detail_message ~ '^Tiket (.*) dibuat: (.*)$';
UPDATE audit_logs SET detail_en = regexp_replace(detail_message, '^(.*) mengubah (TKT-[0-9]+) → (.*)$', '\1 changed \2 → \3')
  WHERE detail_en IS NULL AND action_type = 'TICKET_STATUS' AND detail_message ~ '^(.*) mengubah (TKT-[0-9]+) → (.*)$';
UPDATE audit_logs SET detail_en = replace(replace(regexp_replace(detail_message, '^(.*) menghapus tiket (\S+) ''(.*)'' milik (\S+) \(kategori (.*), status (.*), dibuat (.*), ditutup (.*), ([0-9]+ pesan, [0-9]+ lampiran)\)$', '\1 deleted ticket \2 ''\3'' of \4 (category \5, status \6, created \7, closed \8, \9)'), ' pesan, ', ' messages, '), ' lampiran', ' attachments')
  WHERE detail_en IS NULL AND action_type = 'TICKET_DELETE' AND detail_message ~ '^(.*) menghapus tiket (\S+) ''(.*)'' milik (\S+) \(kategori (.*), status (.*), dibuat (.*), ditutup (.*), ([0-9]+ pesan, [0-9]+ lampiran)\)$';
UPDATE audit_logs SET detail_en = regexp_replace(detail_message, '^(.*) mengajukan Infra Request (\S+) \((.*)\)$', '\1 submitted infrastructure request \2 (\3)')
  WHERE detail_en IS NULL AND action_type = 'INFRA_REQUEST_CREATE' AND detail_message ~ '^(.*) mengajukan Infra Request (\S+) \((.*)\)$';
UPDATE audit_logs SET detail_en = regexp_replace(detail_message, '^(.*) mengubah Infra Request (\S+) \((.*)\) milik (\S+) → (.*)$', '\1 changed infrastructure request \2 (\3) of \4 → \5')
  WHERE detail_en IS NULL AND action_type = 'INFRA_REQUEST_STATUS' AND detail_message ~ '^(.*) mengubah Infra Request (\S+) \((.*)\) milik (\S+) → (.*)$';
UPDATE audit_logs SET detail_en = regexp_replace(detail_message, '^(.*) menghapus Infra Request (\S+) \((.*)\) milik (\S+) \(status (.*), dibuat (.*), ditinjau (.*), ([0-9]+) pesan, ([0-9]+) berkas\)$', '\1 deleted infrastructure request \2 (\3) of \4 (status \5, created \6, reviewed \7, \8 messages, \9 files)')
  WHERE detail_en IS NULL AND action_type = 'INFRA_REQUEST_DELETE' AND detail_message ~ '^(.*) menghapus Infra Request (\S+) \((.*)\) milik (\S+) \(status (.*), dibuat (.*), ditinjau (.*), ([0-9]+) pesan, ([0-9]+) berkas\)$';
-- Pesan sistem di percakapan tiket.
UPDATE ticket_messages SET message_en = regexp_replace(message, '^Status diubah ke (.*) oleh (.*) \((.*)\)$', 'Status changed to \1 by \2 (\3)')
  WHERE message_en IS NULL AND sender_id IS NULL AND message ~ '^Status diubah ke (.*) oleh (.*) \((.*)\)$';
